<?php

namespace UserBundle\Repository;

/**
 * dbNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dbNameRepository extends \Doctrine\ORM\EntityRepository
{
}
