<?php

namespace UserBundle\Repository;

/**
 * isLogedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class isLogedRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLogedUser($systemid, $userid) {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.systemid = :systemid')
            ->andWhere('u.userid <> :userid')
            ->andWhere('u.isloged = true')
            ->setParameter('systemid',$systemid)
            ->setParameter('userid',$userid)
        ;

        return $qb->getQuery()->getResult();
    }
}
