<?php

namespace CalendarBundle\Repository;

/**
 * ServiceCaseStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCaseStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
