<?php

namespace CalendarBundle\Repository;

/**
 * servicecaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicecaseRepository extends \Doctrine\ORM\EntityRepository
{
}
