<?php

namespace CalendarBundle\Repository;

/**
 * ServiceCaseRescheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCaseRescheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
