<?php

namespace CalendarBundle\Repository;

/**
 * StaffColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffColorRepository extends \Doctrine\ORM\EntityRepository
{
}
